/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: katydid (https://sketchfab.com/Katydid.)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/fantasy-floating-island-c9279438c22f489bab34b32287f2032c
Title: Fantasy floating island
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import { a } from '@react-spring/three'

import islandScene from '../assets/fantasy_floating_island.glb'

const Island = (props) => {
  const islandRef = useRef()
  const { nodes, materials } = useGLTF(islandScene)
  
  return (
    <a.group ref={islandRef} {...props}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={0.01}>
          <group position={[-9240.4, 0, 1524.369]}>
            <mesh geometry={nodes.FrontSide_0.geometry} material={materials.TextureMaterial_89} />
            <mesh geometry={nodes.FrontSide_1.geometry} material={materials.TextureMaterial_89_0} />
            <mesh geometry={nodes.FrontSide_2.geometry} material={materials.TextureMaterial_89_1} />
            <mesh geometry={nodes.FrontSide_3.geometry} material={materials.TextureMaterial_89_2} />
            <mesh geometry={nodes.FrontSide_4.geometry} material={materials.TextureMaterial_89_3} />
            <mesh geometry={nodes.FrontSide_5.geometry} material={materials.TextureMaterial_89_4} />
            <mesh geometry={nodes.FrontSide_6.geometry} material={materials.TextureMaterial_89_5} />
            <mesh geometry={nodes.FrontSide_7.geometry} material={materials.TextureMaterial_89_6} />
            <mesh geometry={nodes.FrontSide_8.geometry} material={materials.TextureMaterial_89_7} />
            <mesh geometry={nodes.FrontSide_9.geometry} material={materials.TextureMaterial_89_8} />
            <mesh geometry={nodes.FrontSide_10.geometry} material={materials.TextureMaterial_89_9} />
            <mesh geometry={nodes.FrontSide_11.geometry} material={materials.TextureMaterial_89_10} />
            <mesh geometry={nodes.FrontSide_12.geometry} material={materials.TextureMaterial_89_11} />
            <mesh geometry={nodes.FrontSide_13.geometry} material={materials.TextureMaterial_89_12} />
            <mesh geometry={nodes.FrontSide_14.geometry} material={materials.TextureMaterial_89_13} />
            <mesh geometry={nodes.FrontSide_15.geometry} material={materials.TextureMaterial_89_14} />
            <mesh geometry={nodes.FrontSide_16.geometry} material={materials.TextureMaterial_89_15} />
            <mesh geometry={nodes.FrontSide_17.geometry} material={materials.TextureMaterial_89_16} />
            <mesh geometry={nodes.FrontSide_18.geometry} material={materials.TextureMaterial_89_17} />
            <mesh geometry={nodes.FrontSide_19.geometry} material={materials.TextureMaterial_89_18} />
            <mesh geometry={nodes.FrontSide_20.geometry} material={materials.TextureMaterial_89_19} />
            <mesh geometry={nodes.FrontSide_21.geometry} material={materials.TextureMaterial_89_20} />
            <mesh geometry={nodes.FrontSide_22.geometry} material={materials.TextureMaterial_89_21} />
            <mesh geometry={nodes.FrontSide_23.geometry} material={materials.TextureMaterial_89_22} />
            <mesh geometry={nodes.FrontSide_24.geometry} material={materials.Merged_materials} />
            <mesh geometry={nodes.FrontSide_25.geometry} material={materials.TextureMaterial_89_23} />
            <mesh geometry={nodes.FrontSide_26.geometry} material={materials.TextureMaterial_89_24} />
            <mesh geometry={nodes.FrontSide_27.geometry} material={materials.TextureMaterial_89_25} />
            <mesh geometry={nodes.FrontSide_28.geometry} material={materials.Merged_materials} />
            <mesh geometry={nodes.FrontSide_29.geometry} material={materials.Merged_materials} />
            <mesh geometry={nodes.FrontSide_30.geometry} material={materials.TextureMaterial_89_26} />
            <mesh geometry={nodes.FrontSide_31.geometry} material={materials.TextureMaterial_89_27} />
            <mesh geometry={nodes.FrontSide_32.geometry} material={materials.TextureMaterial_89_28} />
            <mesh geometry={nodes.FrontSide_33.geometry} material={materials.TextureMaterial_89_29} />
            <mesh geometry={nodes.FrontSide_34.geometry} material={materials.TextureMaterial_89_30} />
            <mesh geometry={nodes.FrontSide_35.geometry} material={materials.TextureMaterial_89_31} />
            <mesh geometry={nodes.FrontSide_36.geometry} material={materials.TextureMaterial_89_32} />
            <mesh geometry={nodes.FrontSide_37.geometry} material={materials.TextureMaterial_89_33} />
            <mesh geometry={nodes.FrontSide_38.geometry} material={materials.TextureMaterial_89_34} />
            <mesh geometry={nodes.FrontSide_39.geometry} material={materials.TextureMaterial_89_35} />
            <mesh geometry={nodes.FrontSide_40.geometry} material={materials.TextureMaterial_89_36} />
            <mesh geometry={nodes.FrontSide_41.geometry} material={materials.TextureMaterial_89_37} />
            <mesh geometry={nodes.FrontSide_42.geometry} material={materials.TextureMaterial_89_38} />
            <mesh geometry={nodes.FrontSide_43.geometry} material={materials.TextureMaterial_89_39} />
            <mesh geometry={nodes.FrontSide_44.geometry} material={materials.TextureMaterial_89_40} />
            <mesh geometry={nodes.FrontSide_45.geometry} material={materials.TextureMaterial_89_41} />
            <mesh geometry={nodes.FrontSide_46.geometry} material={materials.TextureMaterial_89_42} />
            <mesh geometry={nodes.FrontSide_47.geometry} material={materials.TextureMaterial_89_43} />
            <mesh geometry={nodes.FrontSide_48.geometry} material={materials.TextureMaterial_89_44} />
            <mesh geometry={nodes.FrontSide_49.geometry} material={materials.TextureMaterial_89_45} />
            <mesh geometry={nodes.FrontSide_50.geometry} material={materials.TextureMaterial_89_46} />
            <mesh geometry={nodes.FrontSide_51.geometry} material={materials.TextureMaterial_89_47} />
            <mesh geometry={nodes.FrontSide_52.geometry} material={materials.TextureMaterial_89_48} />
            <mesh geometry={nodes.FrontSide_53.geometry} material={materials.TextureMaterial_89_49} />
            <mesh geometry={nodes.FrontSide_54.geometry} material={materials.Merged_materials} />
            <mesh geometry={nodes.FrontSide_55.geometry} material={materials.TextureMaterial_89_50} />
            <mesh geometry={nodes.FrontSide_56.geometry} material={materials.TextureMaterial_89_51} />
            <mesh geometry={nodes.FrontSide_57.geometry} material={materials.TextureMaterial_89_52} />
            <mesh geometry={nodes.FrontSide_58.geometry} material={materials.TextureMaterial_89_53} />
            <mesh geometry={nodes.FrontSide_59.geometry} material={materials.TextureMaterial_89_54} />
            <mesh geometry={nodes.FrontSide_60.geometry} material={materials.TextureMaterial_89_55} />
            <mesh geometry={nodes.FrontSide_61.geometry} material={materials.TextureMaterial_89_56} />
            <mesh geometry={nodes.FrontSide_62.geometry} material={materials.TextureMaterial_89_57} />
            <mesh geometry={nodes.FrontSide_63.geometry} material={materials.TextureMaterial_89_58} />
            <mesh geometry={nodes.FrontSide_64.geometry} material={materials.TextureMaterial_89_59} />
            <mesh geometry={nodes.FrontSide_65.geometry} material={materials.Merged_materials} />
            <mesh geometry={nodes.FrontSide_66.geometry} material={materials.Merged_materials} />
            <mesh geometry={nodes.FrontSide_67.geometry} material={materials.TextureMaterial_89_60} />
            <mesh geometry={nodes.FrontSide_68.geometry} material={materials.TextureMaterial_89_61} />
            <mesh geometry={nodes.FrontSide_69.geometry} material={materials.TextureMaterial_89_62} />
            <mesh geometry={nodes.FrontSide_70.geometry} material={materials.TextureMaterial_89_63} />
            <mesh geometry={nodes.FrontSide_71.geometry} material={materials.TextureMaterial_89_64} />
            <mesh geometry={nodes.FrontSide_72.geometry} material={materials.TextureMaterial_89_65} />
            <mesh geometry={nodes.FrontSide_73.geometry} material={materials.TextureMaterial_89_66} />
            <mesh geometry={nodes.FrontSide_74.geometry} material={materials.TextureMaterial_89_67} />
            <mesh geometry={nodes.FrontSide_75.geometry} material={materials.TextureMaterial_89_68} />
            <mesh geometry={nodes.FrontSide_76.geometry} material={materials.TextureMaterial_89_69} />
            <mesh geometry={nodes.FrontSide_77.geometry} material={materials.TextureMaterial_89_70} />
            <mesh geometry={nodes.FrontSide_78.geometry} material={materials.TextureMaterial_89_71} />
            <mesh geometry={nodes.FrontSide_79.geometry} material={materials.TextureMaterial_89_72} />
            <mesh geometry={nodes.FrontSide_80.geometry} material={materials.TextureMaterial_89_73} />
            <mesh geometry={nodes.FrontSide_81.geometry} material={materials.TextureMaterial_89_74} />
            <mesh geometry={nodes.FrontSide_82.geometry} material={materials.TextureMaterial_89_75} />
            <mesh geometry={nodes.FrontSide_83.geometry} material={materials.TextureMaterial_89_76} />
            <mesh geometry={nodes.FrontSide_84.geometry} material={materials.TextureMaterial_89_77} />
            <mesh geometry={nodes.FrontSide_85.geometry} material={materials.TextureMaterial_89_78} />
            <mesh geometry={nodes.FrontSide_86.geometry} material={materials.TextureMaterial_89_79} />
            <mesh geometry={nodes.FrontSide_87.geometry} material={materials.Merged_materials} />
            <mesh geometry={nodes.FrontSide_88.geometry} material={materials.TextureMaterial_89_80} />
            <mesh geometry={nodes.FrontSide_89.geometry} material={materials.TextureMaterial_89_81} />
            <mesh geometry={nodes.FrontSide_90.geometry} material={materials.TextureMaterial_89_82} />
            <mesh geometry={nodes.FrontSide_91.geometry} material={materials.TextureMaterial_89_83} />
            <mesh geometry={nodes.FrontSide_92.geometry} material={materials.TextureMaterial_89_84} />
            <mesh geometry={nodes.FrontSide_93.geometry} material={materials.Merged_materials} />
            <mesh geometry={nodes.FrontSide_94.geometry} material={materials.Merged_materials} />
            <mesh geometry={nodes.FrontSide_95.geometry} material={materials.TextureMaterial_89_85} />
            <mesh geometry={nodes.FrontSide_96.geometry} material={materials.TextureMaterial_89_86} />
            <mesh geometry={nodes.FrontSide_97.geometry} material={materials.TextureMaterial_89_87} />
            <mesh geometry={nodes.FrontSide_98.geometry} material={materials.TextureMaterial_89_88} />
            <mesh geometry={nodes.FrontSide_99.geometry} material={materials.TextureMaterial_89_89} />
            <mesh geometry={nodes.FrontSide_100.geometry} material={materials.Merged_materials} />
            <mesh geometry={nodes.FrontSide_101.geometry} material={materials.Merged_materials} />
            <mesh geometry={nodes.FrontSide_102.geometry} material={materials.TextureMaterial_89_90} />
            <mesh geometry={nodes.FrontSide_103.geometry} material={materials.TextureMaterial_89_91} />
            <mesh geometry={nodes.FrontSide_104.geometry} material={materials.TextureMaterial_89_92} />
            <mesh geometry={nodes.FrontSide_105.geometry} material={materials.TextureMaterial_89_93} />
            <mesh geometry={nodes.FrontSide_106.geometry} material={materials.TextureMaterial_89_94} />
            <mesh geometry={nodes.FrontSide_107.geometry} material={materials.TextureMaterial_89_95} />
            <mesh geometry={nodes.FrontSide_108.geometry} material={materials.Merged_materials} />
            <mesh geometry={nodes.FrontSide_109.geometry} material={materials.TextureMaterial_89_96} />
            <mesh geometry={nodes.BackSide_0.geometry} material={materials.TextureMaterial_89_97} />
            <mesh geometry={nodes.BackSide_0_1.geometry} material={materials.TextureMaterial_89_97} />
            <mesh geometry={nodes.BackSide_0_2.geometry} material={materials.TextureMaterial_89_97} />
            <mesh geometry={nodes.BackSide_1.geometry} material={materials.TextureMaterial_89_52} />
          </group>
        </group>
      </group>
    </a.group>
  );
}


export default Island
